GameStore.WEB/Areas/Admin/Controllers/UsersManagerController.cs
using GameStore.BLL.Infrastrcture;
using GameStore.BLL.Infrastrcture.Identity;
using GameStore.BLL.Predefined;
using GameStore.BLL.Services.UserManagerServices;
using GameStore.WEB.Areas.Admin.Models.UserManagerModels;
using GameStore.WEB.Infrastrcture;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;

namespace GameStore.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = IdentityUserPolicy.role_adminOnly)]
    public class UsersManagerController : Controller
    {
        private readonly IUserManagerService _userManagerService;
        public UsersManagerController(IUserManagerService userManagerService)
        {
            _userManagerService = userManagerService;
        }

        #region PUBLIC METHODS - GET
        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
            ShowUserManagerModel model = await CreateShowModel(TempData);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GetPartialWorkOnData(string userId)
        {
            DataUserManagerModel model = await CreateDataModel(userId);
            return PartialView("_Partial.GetUsers.CreateEditForm", model);
        }

        [HttpGet]
        public async Task <IActionResult> DeleteUserAccount(string userId)
        {
            ResultServiceModel result = await _userManagerService.DeleteUserAsync(User.Identity.Name, userId);
            StandartUserActionTypes actionTypes = new();
            TempData = SetTempDataForInfoAboutLastAction(result, actionTypes.Delete.Id);
            return Json(result);

        }
        #endregion
        #region PUBLIC METHODS - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(DataUserManagerModel model)
        {
            ResultServiceModel result = await _userManagerService.GreateUserAsync(model.AppUser);
            StandartUserActionTypes actionTypes = new();
            TempData = SetTempDataForInfoAboutLastAction(result, actionTypes.Create.Id);
            return RedirectToAction(nameof(GetUsers));
        }      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(DataUserManagerModel model)
        {
            ResultServiceModel result = await _userManagerService.UpdateUserAsync(User.Identity.Name,model.AppUser);
            StandartUserActionTypes actionTypes = new();
            TempData = SetTempDataForInfoAboutLastAction(result, actionTypes.Edit.Id);
            return RedirectToAction(nameof(GetUsers));
        }
        #endregion
        #region PRIVATE METHODS 
        private async Task<ShowUserManagerModel> CreateShowModel(ITempDataDictionary TempData)
        {
            ShowUserManagerModel model = new();
            model.AppUsers = await _userManagerService.GetAllAppUserAsync();
            model.LastAction = new();
            model.LastAction = GetInfoAboutLastActionFromTempData(TempData);
            return model;
        }

        public async Task<DataUserManagerModel> CreateDataModel(string userId)
        {
            DataUserManagerModel model = new();
            PredefinedManager pd = new();
            //Create mode
            if (userId is null)
            {
                model.AppUser = new();            
            }
            //Edit mode
            else
            {
                model.AppUser = await _userManagerService.GetAppUserByEmailAsync(userId);
            }

            model.SelectListItems_Roles = new SelectList(pd.AppRole.RoleList, "Name", "Name");

           return model;
        }
        #endregion      

        #region PRIVATE METHODS - TEMPDATA
        private UserActionResult GetInfoAboutLastActionFromTempData(ITempDataDictionary TempData)
        {
            UserActionResult lastAction = (TempData.ContainsKey("LastAction")) ? JsonConvert.DeserializeObject<UserActionResult>((string)TempData["LastAction"]) : new();
            return lastAction;
        }
        private ITempDataDictionary SetTempDataForInfoAboutLastAction(ResultServiceModel result, int actionTypeId)
        {
            StandartUserActionTypes actionTypes = new();
            string mainMessage = "";
            if (actionTypeId == actionTypes.Create.Id)
            {
                mainMessage = (result.IsSucceeded) ? "Пользователь создан" : "Не удалось создать пользователя";
            }
            else if (actionTypeId == actionTypes.Edit.Id)
            {
                mainMessage = (result.IsSucceeded) ? "Данные пользователя успешно изменены" : $"Не удалось изменить данные пользователя";
            }

            else if (actionTypeId == actionTypes.Delete.Id)
            {
                mainMessage = (result.IsSucceeded) ? "Пользователь успешно удалён" : $"Не удалось удалить пользователя";
            }

            UserActionResult lastAction = new();
            lastAction.Id = actionTypeId;
            lastAction.IsSuccess = result.IsSucceeded;
            lastAction.DopInfo = mainMessage + ". " + result.ErrorMes;
            TempData["LastAction"] = JsonConvert.SerializeObject(lastAction);
            return TempData;

        }
        #endregion
    }
}

GameStore.WEB/Areas/Admin/Views/UsersManager/GetUsers.cshtml
@model ShowUserManagerModel
@{
    ViewData["Title"] = "Управление пользователями";
}

@section js
{
    <script src="~/js/adminarea/tablelanguage.js"></script>
    <script src="~/js/adminarea/usermanagerScr/userstable.js"></script>
     <script>
        // ШАГ 1. НАСТРОЙКА ОБЩЕГО ПОВЕДЕНИЯ МОДАЛОК
        $(document).ready(function () {
            //Вызов DataTable
            InitializationUsersTable();
            //НАСТРОЙКА ПОВЕДЕНИЯ МОДАЛОК - Алерты
            AddHandlerClickForButtonsOfActionModals('modalUserManagerData', 'userManager');

            //НАСТРОЙКА ПОВЕДЕНИЯ МОДАЛОК: Setting modal Create & Edit
            AddHandlerShownModalForCreateEditModal("modalUserManagerData", "userDataManagerForm");
        });
        // ШАГ 2. НАСТРОЙКА МАРШРУТОВ
        function GetURLForAjaxByActionType(actionType) {
            var url = "";
            switch (actionType) {
                case "edit":
                    url = '@Url.Action("GetPartialWorkOnData", "UsersManager")';
                    break;
                case "delete":
                    url = '@Url.Action("DeleteUserAccount", "UsersManager")';
                    break;
            }
            return url;
        }
        // ШАГ 3. ВЫЗОВ ДОПОЛНИТЕЛЬНЫХ ФУНКЦИЙ В ГЛАВНОМ AJAX МЕТОДЕ
        function SettingBehaviorOfModalWindow(boxId, section) { }

    </script>
}

<h1>Управление пользователями</h1>
<a asp-controller="Home" asp-action="Index" class="btn btn-outline-primary">Вернутся к выбору разделов</a>


<div id="tableWrapper" class="row tableWrapper">
    @await Html.PartialAsync("_Partial.GetUsers.Table", Model)
</div>

<div id="modalWrapper">

</div>
<div id="modalActionWrapper">
    @await Html.PartialAsync("_Partial.Action.DataNotSaved")
    @await Html.PartialAsync("_Partial.Action.Warning")
    @await Html.PartialAsync("_Partial.Action.Success")
    @await Html.PartialAsync("_Partial.Action.Error")
</div>

<div id="lastActionDataWrapper">
    @await Html.PartialAsync("_Partial.ActionResult", Model.LastAction)
</div>

GameStore.WEB/Areas/Admin/Views/UsersManager/_Partial.GetUsers.CreateEditForm.cshtml
@model DataUserManagerModel
@{
    bool IsCreateMethod = (Model.AppUser.Email is null) ? true : false;
    string methodName = (IsCreateMethod) ? "CreateUser" : "EditUser";
}

<div class="modal fade modal-js" id="modalUserManagerData" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">@((IsCreateMethod) ? "Создание учётной записи": "Редактирование учётной записи")</h5>
            </div>
            <form id="userDataManagerForm" asp-area="Admin" asp-controller="UsersManager" asp-action="@methodName" method="post">
                <input asp-for=AppUser.Id hidden/>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for=AppUser.Email>Email:</label>
                        <input asp-for=AppUser.Email type="email" class="form-control" aria-describedby="emailHelp" placeholder="example@gmail.com" autocomplete="off" />
                        <span asp-validation-for="AppUser.Email" class="validError"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for=AppUser.UserRoleName>Роль:</label>
                        <select asp-for=AppUser.UserRoleName asp-items=Model.SelectListItems_Roles class="form-control"
                                data-val="true" data-val-required="Поле обязательно для заполнения!">
                            <option selected disabled>Выберите роль</option>
                         
                        </select>
                        <span asp-validation-for="AppUser.UserRoleName" class="validError"></span>
                    </div>

                    @if(IsCreateMethod is false)
                    {
                        <div class="form-group form-check form-switch">
                            <input type="checkbox" asp-for=AppUser.IsBanned class="form-check-input" />
                            <label class="form-check-label" asp-for=AppUser.IsBanned>Блокировка</label>
                        </div>
                    }
          

                </div>
                <div class="modal-footer">
                    <button type="button" id="btnBackFromCreateEditMode" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

GameStore.WEB/Areas/Admin/Views/UsersManager/_Partial.GetUsers.Table.cshtml
@model ShowUserManagerModel

@functions
{
    string GetStingValue(bool objectBool)
    {
        return (objectBool) ? "Да" : "Нет";
    }
}

<table id="usersTable" class="table table-striped display">
    <thead>
        <tr>
            <th>Id</th>
            <th>Аватар</th>
            <th>Email</th>
            <th>Статус</th>
            <th>Роль</th>
            <th>Email подтверждён</th>
            <th>2FA включена</th>
            <th>Последнее посещение</th>
        </tr>
    </thead>
    <tbody>

        @foreach(var user in Model.AppUsers)
        {

            <tr>
                <td>@user.CustomUserId</td>

                @if (user.AvatarImage.Length == 0)
                {
                    <td> <img src="~/img/useravatars/user.jpg" class="avatarInTable rounded-circle" /> </td>
                }
                else
                {
                    <td>
                        @Html.Raw("<img class='avatarInTable rounded-circle' src=\"data:image/jpeg;base64,"
                                 + Convert.ToBase64String(user.AvatarImage) + "\" />")
                    </td>
                }

                <td>@user.Email</td>
                <td>@((user.IsBanned is false) ? "Активный" :  $"Заблокирован (до: {user.LockoutEnd.Value.ToString("dd/MM/yyyy HH:mm")})")</td>
                <td>@user.UserRoleName</td>
                <th>@GetStingValue(user.EmailConfirmed)</th>
                <th>@GetStingValue(user.TwoFactorEnabled)</th>
                <td>@((user.LastVisit.HasValue) ? user.LastVisit.Value.ToString("dd/MM/yyyy"):"Не заходил")</td>
            </tr>
        }

    </tbody>
</table>