GameStore.WEB/Areas/Admin/Controllers/DictionariesController.cs
using GameStore.BLL.DTO.Dictionaries;
using GameStore.BLL.Infrastrcture;
using GameStore.BLL.Infrastrcture.Identity;
using GameStore.BLL.Services.DictionariesServices;
using GameStore.DAL.Entities.Dictionaries;
using GameStore.WEB.Areas.Admin.Models.DictionariesModels;
using GameStore.WEB.Infrastrcture;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;

namespace GameStore.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = IdentityUserPolicy.role_adminOnly)]
    public class DictionariesController : Controller
    {
        private readonly DictionaryService<Genre, GenreDTO> _genreService;
        private readonly DictionaryService<GameDeveloper, GameDeveloperDTO> _gameDevService;
        private readonly DictionaryService<GamePlatform, GamePlatformDTO> _gamePlatformService;
        private readonly DictionaryService<GameLabel, GameLabelDTO> _gameLableService;

        public DictionariesController(DictionaryService<Genre, GenreDTO> genreService,
                                      DictionaryService<GameDeveloper, GameDeveloperDTO> gameDevService,
                                      DictionaryService<GamePlatform, GamePlatformDTO> gamePlatformService,
                                      DictionaryService<GameLabel, GameLabelDTO> gameLableService)
        {
            _genreService = genreService;
            _gameDevService = gameDevService;
            _gamePlatformService = gamePlatformService;
            _gameLableService = gameLableService;
        }


        #region PUBLIC METHODS - GET
        [HttpGet]
        public IActionResult Index()
        {
            ShowDictionatyModel model = new();
            model.LastAction = GetInfoAboutLastActionFromTempData(TempData);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetDataForTable(string sectionName)
        {
            ShowDictionatyModel model = await CreateShowModel(sectionName, TempData);
            return PartialView("_Partial.Dictionaries.List", model);
        }

        [HttpGet]
        public async Task<IActionResult> GetPartialWorkOnData(int id, string sectionName)
        {
            DataDictionaryModel model = await CreateDataModel(id, sectionName);
            return PartialView("_Partial.Dictionaries.CreateEditForm", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteDictionary (int id, string sectionName)
        {
            ResultServiceModel result = new();
            DictionariesTypes dictionariesTypes = new();

            if (sectionName == dictionariesTypes.d_genre.SectionName)
            {
                result = await _genreService.DeleteEntity(id);
                                      
            }
            else if (sectionName == dictionariesTypes.d_gamDev.SectionName)
            {
                result = await _gameDevService.DeleteEntity(id);
                                            
            }
            else if (sectionName == dictionariesTypes.d_gamPlat.SectionName)
            {
                result = await _gamePlatformService.DeleteEntity(id);
                                          
            }
            else if (sectionName == dictionariesTypes.d_gamLabel.SectionName)
            {
                result = await _gameLableService.DeleteEntity(id);                        
            }

            StandartUserActionTypes actionTypes = new();
            int sectionOrderId = dictionariesTypes.DictionaryTypesList.Where(x=>x.SectionName == sectionName).First().OrderId;
            TempData = SetTempDataForInfoAboutLastAction(result, actionTypes.Delete.Id, sectionOrderId);
            return Json(result);
        }
        #endregion

        #region PUBLIC METHODS - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEditDictionary(DataDictionaryModel model)
        {
            ResultServiceModel result = new();
            DictionariesTypes dictionariesTypes = new();
            
            if(model.SectionOrderId == dictionariesTypes.d_genre.OrderId)
            {
                result = (model.IsCreateMode) ? await _genreService.CreateEntity(model.Genre) 
                                              : await _genreService.UpdateEntity(model.Genre);
            }
            else if (model.SectionOrderId == dictionariesTypes.d_gamDev.OrderId)
            {
                result = (model.IsCreateMode) ? await _gameDevService.CreateEntity(model.GameDeveloper)
                                              : await _gameDevService.UpdateEntity(model.GameDeveloper);
            }
            else if (model.SectionOrderId == dictionariesTypes.d_gamPlat.OrderId)
            {
                result = (model.IsCreateMode) ? await _gamePlatformService.CreateEntity(model.GamePlatform)
                                              : await _gamePlatformService.UpdateEntity(model.GamePlatform);
            }
            else if (model.SectionOrderId == dictionariesTypes.d_gamLabel.OrderId)
            {
                result = (model.IsCreateMode) ? await _gameLableService.CreateEntity(model.GameLabel)
                                              : await _gameLableService.UpdateEntity(model.GameLabel);
            }

            StandartUserActionTypes actionTypes = new();
            TempData = SetTempDataForInfoAboutLastAction(result, (model.IsCreateMode) ? actionTypes.Create.Id : actionTypes.Edit.Id ,model.SectionOrderId);
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region PRIVATE METHODS 
        private async Task<ShowDictionatyModel> CreateShowModel(string sectionName, ITempDataDictionary TempData)
        {
            ShowDictionatyModel model = new();
            DictionariesTypes dictionariesTypes = new();
            if (dictionariesTypes.d_genre.SectionName == sectionName)
            {
                model.Genres = await _genreService.GetAllEntitiesAsync();
                model.DictionaryName = dictionariesTypes.d_genre.RuName;

                model.GameLabels = new();
                model.GameDevelopers = new();
                model.GamePlatforms = new();
            }
            else if (dictionariesTypes.d_gamDev.SectionName == sectionName)
            {
                model.GameDevelopers = await _gameDevService.GetAllEntitiesAsync();
                model.DictionaryName = dictionariesTypes.d_gamDev.RuName;

                model.Genres = new();
                model.GamePlatforms = new();
                model.GameLabels = new();

            }
            else if (dictionariesTypes.d_gamPlat.SectionName == sectionName)
            {
                model.GamePlatforms = await _gamePlatformService.GetAllEntitiesAsync();
                model.DictionaryName = dictionariesTypes.d_gamPlat.RuName;

                model.Genres = new();
                model.GameDevelopers = new();
                model.GameLabels = new();
            }
            else if (dictionariesTypes.d_gamLabel.SectionName == sectionName)
            {
                model.GameLabels = await _gameLableService.GetAllEntitiesAsync();
                model.DictionaryName = dictionariesTypes.d_gamLabel.RuName;

                model.Genres = new();
                model.GameDevelopers = new();
                model.GamePlatforms = new();
            }
            model.LastAction = GetInfoAboutLastActionFromTempData(TempData);

            return model;
        }

        private async Task<DataDictionaryModel> CreateDataModel(int id, string sectionName)
        {
            DataDictionaryModel model = new();
            DictionariesTypes dictionariesTypes = new();
            string titleText = string.Empty;

            //CREATE MODE
            if (id == 0)
            {
                model.IsCreateMode = true;
            }
            //EDIT MODE
            else
            {
                if (sectionName == dictionariesTypes.d_genre.SectionName)
                {
                    model.Genre = await _genreService.GetEntityById(id);
                }
                else if (sectionName == dictionariesTypes.d_gamDev.SectionName)
                {
                    model.GameDeveloper = await _gameDevService.GetEntityById(id);
                }
                else if (sectionName == dictionariesTypes.d_gamPlat.SectionName)
                {
                    model.GamePlatform = await _gamePlatformService.GetEntityById(id);
                }
                else if (sectionName == dictionariesTypes.d_gamLabel.SectionName)
                {
                    model.GameLabel = await _gameLableService.GetEntityById(id);
                }

                model.IsCreateMode = false;
            }

            model.TitleNameForm = CreateTextTitleForFormCreateEdit(sectionName);
            model.SectionOrderId = dictionariesTypes.DictionaryTypesList.Where(x=>x.SectionName == sectionName).First().OrderId;
            return model;
        }

        private string CreateTextTitleForFormCreateEdit(string sectionName)
        {
            DictionariesTypes dictionariesTypes = new();
            string titleText = string.Empty;

            if (sectionName == dictionariesTypes.d_genre.SectionName)
            {
                titleText = "Жанра";
            }
            else if (sectionName == dictionariesTypes.d_gamDev.SectionName)
            {
                titleText = "Разработчика";
            }
            else if (sectionName == dictionariesTypes.d_gamPlat.SectionName)
            {
                titleText = "Платформы";
            }
            else if (sectionName == dictionariesTypes.d_gamLabel.SectionName)
            {
                titleText = "Особенности игры";
            }

            return titleText;

GameStore.WEB/Areas/Admin/Views/Dictionaries/Index.cshtml
@model ShowDictionatyModel
@{
    ViewData["Title"] = "Словари";
    DictionariesTypes types = new();
}

@section js{
    <script src="~/js/adminarea/dictionaries/dictionariesDT.js"></script> 
    <script src="~/js/adminarea/tablelanguage.js"></script>
    <script src="~/js/adminarea/dictionaries/dictionariesManager.js"></script>

    <script>
        // ШАГ 1. НАСТРОЙКА ОБЩЕГО ПОВЕДЕНИЯ МОДАЛОК
        $(document).ready(function () {
           
            //НАСТРОЙКА ПОВЕДЕНИЯ МОДАЛОК - Алерты
            AddHandlerClickForButtonsOfActionModals('modalDictionaryData', 'dictionaries');

            //НАСТРОЙКА ПОВЕДЕНИЯ МОДАЛОК: Setting modal Create & Edit
            AddHandlerShownModalForCreateEditModal("modalDictionaryData", "dictionaryDataForm");

        });

        // ШАГ 2. НАСТРОЙКА МАРШРУТОВ
        function GetURLForAjaxByActionType(actionType) {
            var url = "";
            switch (actionType) {
                case "edit":
                     url = '@Url.Action("GetPartialWorkOnData", "Dictionaries")';
                    break;
                case "delete":
                      url = '@Url.Action("DeleteDictionary", "Dictionaries")';
                    break;
            }
            return url;
        }
        // ШАГ 3. ВЫЗОВ ДОПОЛНИТЕЛЬНЫХ ФУНКЦИЙ В ГЛАВНОМ AJAX МЕТОДЕ
        function SettingBehaviorOfModalWindow(boxId, section) { }

        //НАСТРОЙКА ДЛЯ ПОКАЗА ДАННЫХ В DATATABLE
        function GetUrlFotAjaxActionGetData()
        {
           var url = '@Url.Action("GetDataForTable","Dictionaries")';
           return url;
        }
        function SettingsDictionaryDataTable()
        {
           //Вызов DataTable
            InitializationUsersTable();
        }

    </script>
}
<h1>Словари</h1>
<a asp-controller="Home" asp-action="Index" class="btn btn-outline-primary">Вернутся к выбору разделов</a>

<div class="row mt-5">
    <div class="col-4  ">
        <div class="d-grid gap-2 col-6 mx-auto">

            @foreach(var btn in types.DictionaryTypesList)
            {
                <button type="button" id="d_@btn.OrderId" data-section="@btn.SectionName" class="btn btn-outline-primary js-dictionaryBtn">@btn.RuName</button>
            }
           
        </div>
      
    </div>
    <div class="col borderS">
        <div id="js-showTable">
          <h4>Выберите раздел</h4>
        </div>
    </div>
</div>

<div id="modalWrapper">

</div>

<div id="modalActionWrapper">
    @await Html.PartialAsync("_Partial.Action.DataNotSaved")
    @await Html.PartialAsync("_Partial.Action.Warning")
    @await Html.PartialAsync("_Partial.Action.Success")
    @await Html.PartialAsync("_Partial.Action.Error")
</div>

<div id="lastActionDataWrapper">
    @await Html.PartialAsync("_Partial.ActionResult", Model.LastAction)
</div>

GameStore.WEB/Areas/Admin/Views/Dictionaries/_Partial.Dictionaries.CreateEditForm.cshtml
@model DataDictionaryModel

@{
    DictionariesTypes dictionariesTypes = new();
}

<div class="modal fade modal-js" id="modalDictionaryData" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">@((Model.IsCreateMode) ? $"Добавление {Model.TitleNameForm}" 
                                                                                        : $"Редактирование {Model.TitleNameForm}")</h5>
            </div>
            <form id="dictionaryDataForm" asp-area="Admin" asp-controller="Dictionaries" asp-action="CreateEditDictionary" method="post">
              
                <input asp-for=SectionOrderId  readonly hidden/>
                <input asp-for=IsCreateMode readonly hidden />
               
                @if (Model.SectionOrderId == dictionariesTypes.d_genre.OrderId)
                {
                    <div class="modal-body">
                        <div class="form-group">
                            <input asp-for=Genre.Id readonly hidden/>
                            <label asp-for=Genre.Name>Наименование:</label>
                            <input asp-for=Genre.Name type="text" class="form-control" placeholder="Введите наименование @Model.TitleNameForm.ToLower()" autocomplete="off" />
                            <span asp-validation-for="Genre.Name" class="validError"></span>
                        </div>
                    </div>
                }
                else if (Model.SectionOrderId == dictionariesTypes.d_gamDev.OrderId)
                {
                    <div class="modal-body">
                        <div class="form-group">
                            <input asp-for=GameDeveloper.Id readonly hidden />
                            <label asp-for=GameDeveloper.Name>Наименование:</label>
                            <input asp-for=GameDeveloper.Name type="text" class="form-control" placeholder="Введите наименование @Model.TitleNameForm.ToLower()" autocomplete="off" />
                            <span asp-validation-for="GameDeveloper.Name" class="validError"></span>
                        </div>
                    </div>
                }
                else if (Model.SectionOrderId == dictionariesTypes.d_gamPlat.OrderId)
                {
                    <div class="modal-body">
                        <div class="form-group">
                            <input asp-for=GamePlatform.Id readonly hidden />
                            <label asp-for=GamePlatform.Name>Наименование:</label>
                            <input asp-for=GamePlatform.Name type="text" class="form-control" placeholder="Введите наименование @Model.TitleNameForm.ToLower()" autocomplete="off" />
                            <span asp-validation-for="GamePlatform.Name" class="validError"></span>
                        </div>
                    </div>
                }
                else if (Model.SectionOrderId == dictionariesTypes.d_gamLabel.OrderId)
                {
                    <div class="modal-body">
                        <div class="form-group">
                            <input asp-for=GameLabel.Id readonly hidden />
                            <label asp-for=GameLabel.Name>Наименование:</label>
                            <input asp-for=GameLabel.Name type="text" class="form-control" placeholder="Введите наименование @Model.TitleNameForm.ToLower()" autocomplete="off" />
                            <span asp-validation-for="GameLabel.Name" class="validError"></span>
                        </div>
                    </div>
                }


                <div class="modal-footer">
                    <button type="button" id="btnBackFromCreateEditMode" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

GameStore.WEB/Areas/Admin/Views/Dictionaries/_Partial.Dictionaries.List.Table.cshtml
@model ShowDictionatyModel

<table id="dictionariesTable" class="table table-striped display">
    <thead>
        <tr>
            <th>Id</th>
            <th>Наименование</th>
        </tr>
    </thead>
    <tbody>

        @if(Model.Genres.Count != 0)
        {
            @foreach (var obj in Model.Genres)
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Name</td>
                </tr>
            }
        }
        else if (Model.GameDevelopers.Count != 0)
        {
            @foreach (var obj in Model.GameDevelopers)
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Name</td>
                </tr>
            }
        }
        else if (Model.GamePlatforms.Count != 0)
        {
            @foreach (var obj in Model.GamePlatforms)
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Name</td>
                </tr>
            }
        }

        else if (Model.GameLabels.Count != 0)
        {
            @foreach (var obj in Model.GameLabels)
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Name</td>
                </tr>
            }
        }

       
       
    </tbody>
</table>

GameStore.WEB/Areas/Admin/Views/Dictionaries/_Partial.Dictionaries.List.cshtml
@model ShowDictionatyModel
<h4>@Model.DictionaryName</h4>
<div id="tableWrapper" class="row tableWrapper">
    @await Html.PartialAsync("_Partial.Dictionaries.List.Table", Model)
</div>